services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  distributedcache:
    image: redis

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: src
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: src
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile
  
  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management 

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: src
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: src
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog: # Dodao zbog Postgres NoSQL koju koristim u Catalog
  postgres_basket: # Dodao zbog Postgres NoSQL koju koristim u Basket
  sqlite_data: # Dodao zbog SQLite koju koristim u Discount




