services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  catalogdb:   # Catalog DB Docker server
    image: postgres # Mora ovamo ime slike PostgreSQL (via Marten as Postgre NoSQL)
  
  basketdb:    # Basket DB Docker server 
    image: postgres # Mora ovako ime slike jer koristim PostgreSQL (via Marten as Postgre NoSQL)
  
  distributedcache:
    image: redis   # Mora ovako ime slike za Redis.

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: src
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: src
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile
  
  orderdb:
    image: mcr.microsoft.com/mssql/server # Mora ovako ime slike za SQL Server

  messagebroker:
    image: rabbitmq:management    # Mora ovako ime slike za RabbitMQ

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: src
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: src
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog: # Dodao zbog Postgres NoSQL koju koristim u Catalog
  postgres_basket: # Dodao zbog Postgres NoSQL koju koristim u Basket
  sqlite_data: # Dodao zbog SQLite koju koristim u Discount




